[default]
address = "127.0.0.1"
port = 8000
workers = 8
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "normal"

[default.limits]
form = "50 MiB"
json = "5 MiB"
msgpack = "5 MiB"
data-form = "50 MiB"
file = "50 MiB"

[debug]
address = "127.0.0.1"
port = 8000
workers = 8
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "normal"

[debug.limits]
form = "50 MiB"
json = "5 MiB"
msgpack = "5 MiB"
data-form = "50 MiB"
file = "50 MiB"

[release]
address = "0.0.0.0"
port = 8000
workers = 8
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "normal"
