name: Build and Test

on: [push]

jobs:
  build:
    name: Build Ubuntu
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          DATABASE_HOST: localhost
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: Setup Database
        env:
          PGPASSWORD: postgres
          DATABASE_URL: postgres://postgres:postgres@localhost/thearningdb

        run: |
          sudo apt update
          sudo apt install -y postgresql postgresql-contrib
          sudo pg_ctlcluster 12 main start
          psql -h localhost -U postgres -c 'CREATE DATABASE "thearningdb";'
          psql -h localhost -U postgres -c 'CREATE DATABASE "thearningtest";'
      - name: Setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustc, cargo, rust-std, clippy, rustfmt
      - name: Install diesel
        run: |
          cargo install diesel_cli --no-default-features --features "postgres"
          echo "DATABASE_URL=postgres://postgres:postgres@localhost/thearningdb" >> .env
          echo "DATABASE_URL_TEST=postgres://postgres:postgres@localhost/thearningtest" >> .env
          echo "SITE_URL=localhost:8000" >> .env
          export "PATH=~/.cargo/bin:$PATH"
          echo "SECRETS=7N4SK1BX96xEOotwddzlJGoxn2HVLzFRp+wxuCJRgmM=" >> .env
          diesel migration run --database-url "postgres://postgres:postgres@localhost/thearningdb"
          diesel migration run --database-url "postgres://postgres:postgres@localhost/thearningtest"
      - name: Build
        run: |
          cargo build
      - name: Test
        run: |
          mkdir -p media/classes media/profiles media/attachments
          cargo test -- --test-threads 1
          rm -rf media
