name: Build and Test Ayaya

on: [push]

jobs:
  build:
    name: Build Ayaya
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustc, cargo, rust-std, clippy, rustfmt
      
      - name: Build
        run: |
          cd ayaya/
          cargo build
      
      - name: Test
        env:
          test_email: ${{ secrets.TEST_EMAIL }}
          test_password: ${{ secrets.TEST_PASSWORD }}
          test_server: ${{ secrets.TEST_SERVER }}
        run: |
          export TEST_EMAIL=$test_email
          export TEST_PASSWORD=$test_password
          export TEST_SERVER=$test_server
          
          cd ayaya/
          cargo test

